### ISSUE TITLE
I tested the trojan on myself... am I safe?

### ISSUE THREAD

**Issue by V4NB0T** [Gumbobrot/Hazard-Token-Grabber-v2#16]
its working alright but im currently concered for my own safety and my machine :'(

**Comment by V4NB0T** [comment]
done those, is it also safe to log in & out of things jsut to be sure as logging back in resets cookies

**Comment by Gumbobrot** [comment]
> done those, is it also safe to log in & out of things jsut to be sure as logging back in resets cookies

## What to do now?
**If you ran your own file with your own webhook set from your own server:**
Yes, but you don't even need to do those things because nobody has access to them anymore. If you did the things I told you before, you removed the injection and startup file(s).

## But!

**If you ran any grabber from another person with an unknown webhook:**
Instantly change ALL your passwords, also Discord and EVERY mail account you own.

**Comment by Gumbobrot** [comment]
## Contact
If you ran into any other trouble, check out the readme form this project to join our discord or add me on Discord (the discord link on the readme is outdated so wait for me to fix it and put the new invite link or use the invite link i posted here. because of the dispute with the other devs, I created my own new discord server, so dont join the one from the readme. Currently, the old one is still in it.)
https://discord.com/users/1075072806892621874
